### ISSUE TITLE
[Bug] crashes on start TypeError: devices.forEach is not a function

### ISSUE THREAD

**Issue by benpoe** [itavero/homebridge-z2m#13]
**Describe the bug*
did a fresh install of the plugin,configureed it, restart homebridge and gets an error in the log which crashes homebridge as a whole.

**To Reproduce**
1. Go to ' plugin->install '
2. fil in settings
3. rstart home bridge

**Expected behavior**
expect the plugin to work or at least give some pointers one what went wrong.

**MQTT messages**
If possible, please provide the following messages:
* The device identification from `zigbee2mqtt/bridge/config/devices`
* Status update from `zigbee2mqtt/[FRIENDLY_NAME]`
* Messages published by this plugin that might be to your issue (can also be seen in the homebridge logs)

**Versions used**
Please provide the version of the following pieces of software:
 - This plugin 0.0.6
 - Homebridge 1.2.3
 - Zigbee2mqtt 
 - Homebridge Config UI X (if applicable)
```
  {
            "mqtt": {
                "base_topic": "zigbee2mqtt",
                "server": "mqtt://192.168.1.25:1883",
                "user": "user",
                "password": "password",
                "client_id": "",
                "reject_unauthorized": false,
                "keepalive": 60,
                "version": 3
            },
            "platform": "zigbee2mqtt"
        }
```

`9/30/2020, 10:06:02 AM] Homebridge v1.2.3 is running on port 52624.

[9/30/2020, 10:06:02 AM] [zigbee2mqtt] Connected to MQTT server

[9/30/2020, 10:06:06 AM] TypeError: devices.forEach is not a function

    at Zigbee2mqttPlatform.handleReceivedDevices (/homebridge/node_modules/homebridge-z2m/src/platform.ts:125:13)

    at Zigbee2mqttPlatform.onMessage (/homebridge/node_modules/homebridge-z2m/src/platform.ts:103:12)

    at MqttClient.emit (events.js:315:20)

    at MqttClient._handlePublish (/homebridge/node_modules/homebridge-z2m/node_modules/mqtt/lib/client.js:1271:12)

    at MqttClient._handlePacket (/homebridge/node_modules/homebridge-z2m/node_modules/mqtt/lib/client.js:410:12)

    at work (/homebridge/node_modules/homebridge-z2m/node_modules/mqtt/lib/client.js:321:12)

    at processTicksAndRejections (internal/process/task_queues.js:79:11)`

**Comment by benpoe** [comment]
fixred this. by manually changing mqtt protocol to 3 as mosquitto supports 3.1, the default 4 is not changeable through gui.

**Comment by itavero** [comment]
I wasn't aware that zigbee2mqtt also supports 3 (I based my configuration of of theirs).
I'll update the range of that setting, and see if I can add some log message (something like "No devices found or invalid message received. Maybe check the MQTT version?")

**Comment by itavero** [comment]
I'll probably make a release this week which will include the changes I've suggested above.

**Comment by itavero** [comment]
The next release will include additional logging and a try/catch to prevent the crash.
I've also extended the range of the MQTT version setting in the config UI.
