### ISSUE TITLE
[Feature] Expose Tilt as CurrentHorizontalTiltAngle

### ISSUE THREAD

**Issue by janikmu** [itavero/homebridge-z2m#146]
**Problem description**
Hi, after adding my new device to zigbee-herdsman-converters (https://github.com/Koenkk/zigbee-herdsman-converters/pull/2474) I was quite surprised to not see the tilt value which it exposes in Homebridge. I guess no one until now had a scenario for this? 😄 

**Suggested solution**
We can use the tilt expose
```
{
     "access":7,
     "description":"Tilt of this cover",
     "name":"tilt",
     "property":"tilt",
     "type":"numeric",
     "value_max":100,
     "value_min":0
}
```
as a CurrentHorizontalTiltAngle characteristic with a little mapping of [0%, 100%] to [-90°,90°]. 
The same should then work for TargetHorizontalTiltAngle.

**Describe alternatives you've considered**
none, not implemented

**Additional context**
I have looked into the Cover converter, and position code can largely be imitated, but it should not be required like position,  rather optional as it is an optional characteristic.

**Are you willing to contribute to this feature?**
Yes, I am actively working on https://github.com/itavero/homebridge-z2m/pull/147

**Comment by itavero** [comment]
Thanks for contributing to this plugin.

I remember I thought about adding it, but since I didn't have a device that supported it, I wasn't 100% sure which characteristics to use (horizontal or vertical).

If you have any questions or need help, let me know.

**Comment by itavero** [comment]
> Regarding the optionality of this expose, how should I rewrite the tests? Add another cover that has both?

That's indeed what I would do. The original tests should then _not_ add the new characteristics and the new set of tests should, of course.

**Comment by janikmu** [comment]
I ran into some problems, that I cannot solve just by looking at existing code 😄

First of all, it doesn't seem to like that I just use `callback(null)` as well for the `handleSetTargetVerticalTilt` function that is now bound additionally to the CoverHandler in case of a tilt expose present (as opposed to previously only the `handleSetTargetPosition` function). It get's published, so I see it more as a warning than an error, but this callback is useful for something, I suppose.... Any idea on how to resolve this? 
```
[4/18/2021, 6:58:45 PM] [zigbee2mqtt] DEBUG: target percentage: 50
[4/18/2021, 6:58:45 PM] [zigbee2mqtt] Pending data: {"position":0,"tilt":50}
[4/18/2021, 6:58:45 PM] [homebridge-z2m-tilt] This plugin threw an error from the characteristic 'Target Position': Unhandled error thrown inside write handler for characteristic: This callback function has already been called by someone else; it can only be called one time.. See https://git.io/JtMGR for more info.
[4/18/2021, 6:58:45 PM] [homebridge-z2m-tilt] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at CoverHandler.handleSetTargetVerticalTilt (/home/pi/homebridge-z2m/src/converters/cover.ts:207:5)
    at TargetPosition.emit (events.js:327:22)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1632:16
    at new Promise (<anonymous>)
    at TargetPosition.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:14)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
[4/18/2021, 6:58:45 PM] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x842e14fffea1cd5f/set': '{"position":0,"tilt":50}'
```

Next, I really don't know how to state an **expected absence** in the test for the IKEA blinds that do not expose tilt and should consequently not have the characteristics, what is your proposal for this?

**Comment by itavero** [comment]
The way I've setup the tests it should fail if additional characteristics are being created that have not been "declared" as expected characteristics (if I remember correctly). No explicit action to test this.

Reading the target characteristic is already better than what it used to be. I am curious what your use case is, given that you are only interested in the current state and not interested in setting it.
Setting it can probably be done with other HomeKit apps (like Eve).
I can imagine that tilt could be part of a scene. (I mostly control my IKEA blinds via scenes as well.)

**Comment by janikmu** [comment]
> I am curious what your use case is, given that you are only interested in the current state and not interested in setting it.

Not very usual. For starters, I don't have any Homekit-compatible device. 😄 
Zigbee2MQTT -> Homebridge -> Google Home was - interestingly enough - the easiest route for me if I wanted to use my blinds with Google Home. 

Regarding Current and Target Characteristics: To be honest, I just wanted to have the Current Tilt Angle/Percentage show up at least somewhere accessible, as it is not exposed in the Google Home App as well. I have read something about rotation (https://developers.google.com/assistant/smarthome/traits/rotation) which could act as a handler for setting tilt, but I would need to add this to the Google Smart Home plugin (https://github.com/oznu/homebridge-gsh/) as well, which I might do in the future.

If I add a SET handler for `TargetVerticalTiltAngle` I get an error. It doesn't seem to like that I just use callback(null) as well for the handleSetTargetVerticalTilt function that is now bound additionally to the CoverHandler in case of a tilt expose present (as opposed to previously only the handleSetTargetPosition function). Any idea on how to resolve this?
Additionally, this is just setting the desired tilt angle from a third party (through MQTT), not through Homebridge.

```
[4/18/2021, 6:58:45 PM] [zigbee2mqtt] DEBUG: target percentage: 50
[4/18/2021, 6:58:45 PM] [zigbee2mqtt] Pending data: {"position":0,"tilt":50}
[4/18/2021, 6:58:45 PM] [homebridge-z2m-tilt] This plugin threw an error from the characteristic 'Target Position': Unhandled error thrown inside write handler for characteristic: This callback function has already been called by someone else; it can only be called one time.. See https://git.io/JtMGR for more info.
[4/18/2021, 6:58:45 PM] [homebridge-z2m-tilt] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at CoverHandler.handleSetTargetVerticalTilt (/home/pi/homebridge-z2m/src/converters/cover.ts:207:5)
    at TargetPosition.emit (events.js:327:22)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1632:16
    at new Promise (<anonymous>)
    at TargetPosition.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:14)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
[4/18/2021, 6:58:45 PM] [zigbee2mqtt] Publish to 'zigbee2mqtt/0x842e14fffea1cd5f/set':
```

**Comment by janikmu** [comment]
Quick update: I borrowed an iOS device and installed the Eve app to test setting the tilt. 
I bound it to the wrong target, producing the callback error, this should now be fixed. 

Also, according to the Homekit documentation (https://developer.apple.com/documentation/homekit/hmcharacteristictypecurrenthorizontaltilt) 
it is indeed a tilt of a horizontal slat (thus back to HorizontalTiltAngle characteristic... )

**Comment by janikmu** [comment]
Okay, so I have tested everything with the Eve app and setting the Target works as well - https://github.com/itavero/homebridge-z2m/pull/147 is ready for review then.

**Comment by itavero** [comment]
Been a bit busy at work. I hope I find some time next weekend to have a look at your code.
