### ISSUE TITLE
Latest release is broken: Cannot find module 'hap-nodejs'

### ISSUE THREAD

**Issue by itavero** [itavero/homebridge-z2m#6]
When updating to the latest release the plugin cannot be loaded because:
```
[7/5/2020, 1:41:59 PM] ====================
[7/5/2020, 1:41:59 PM] ERROR LOADING PLUGIN homebridge-z2m:
[7/5/2020, 1:41:59 PM] Error: Cannot find module 'hap-nodejs'
Require stack:
- /usr/local/lib/node_modules/homebridge-z2m/dist/customServices.js
- /usr/local/lib/node_modules/homebridge-z2m/dist/platformAccessory.js
- /usr/local/lib/node_modules/homebridge-z2m/dist/platform.js
- /usr/local/lib/node_modules/homebridge-z2m/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-z2m/src/customServices.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
[7/5/2020, 1:41:59 PM] ====================
```

Currently figuring out how to fix this.. 😥

**Comment by itavero** [comment]
This has to do with the support for the pressure sensor I added. Apparently I made a mistake by including directly from `hap-nodejs`. I do not yet know how to do this properly, so I'm removing the Pressure Sensor support for now.
