### ISSUE TITLE
[Feature] Air Pressure Sensor

### ISSUE THREAD

**Issue by itavero** [itavero/homebridge-z2m#7]
Due to #6, I had to revert the Air Pressure Sensor supports.
I can probably add this support again by applying the same solution as in the homebridge-ring plugin:
https://github.com/dgreif/ring/blob/bb76340bd075235bc7ce0c0353acf79e8924b79c/homebridge/index.ts#L5

(as suggested by dgreif on Discord)

**Comment by itavero** [comment]
Gave the suggestions a try, but it seems that extending is not possible with this "dynamic" construction.

Log from homebridge:
```
[7/12/2020, 9:03:55 PM] ====================
[7/12/2020, 9:03:55 PM] ERROR LOADING PLUGIN homebridge-z2m:
[7/12/2020, 9:03:55 PM] TypeError: Cannot read property 'Service' of undefined
    at Object.<anonymous> (/Users/arnom/Projects/homebridge-z2m/src/customServices.ts:11:44)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/arnom/Projects/homebridge-z2m/src/platformAccessory.ts:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
[7/12/2020, 9:03:55 PM] ====================
```

**Comment by itavero** [comment]
Restored support in cf41e57fd3ccb6e9b384f9d063491ebbbc5402a3
