### ISSUE TITLE
[Bug] plugin crashes

### ISSUE THREAD

**Issue by 1HyperZ** [itavero/homebridge-z2m#810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the z2m plugin crashes every time it starts, started last week and the updates for both z2m and the plugin didnt solve it both are up to date. this is the log:

08/01/2024, 22:04:35] [homebridge-z2m] Restarting Process...
[08/01/2024, 22:04:36] [homebridge-z2m] Launched child bridge with PID 1152
[08/01/2024, 22:04:36] Registering platform 'homebridge-z2m.zigbee2mqtt'
[08/01/2024, 22:04:36] [homebridge-z2m] Loaded homebridge-z2m v1.9.3 child bridge successfully
[08/01/2024, 22:04:37] Loaded 38 cached accessories from cachedAccessories.0ECCABD2C794.

/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1800
            .getCharacteristic(Characteristic_1.Characteristic.Identify)
            ^
TypeError: Cannot read properties of undefined (reading 'getCharacteristic')
    at Accessory._sideloadServices (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1800:13)
    at Function.Accessory.deserialize (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:2188:15)
    at Function.deserialize (/var/lib/homebridge/node_modules/homebridge/src/platformAccessory.ts:172:33)
    at /var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:240:34
    at Array.map (<anonymous>)
    at BridgeService.loadCachedPlatformAccessoriesFromDisk (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:239:58)
    at ChildBridgeFork.startBridge (/var/lib/homebridge/node_modules/homebridge/src/childBridgeFork.ts:142:5)
[08/01/2024, 22:04:37] [homebridge-z2m] Child bridge process ended
[08/01/2024, 22:04:37] [homebridge-z2m] Process Ended. Code: 1, Signal: null
[08/01/2024, 22:04:44] [homebridge-z2m] Restarting Process...

### This plugin

1.9.3

### Homebridge

1.7.0

### Zigbee2MQTT

 1.35.1

### Homebridge Config UI X (if applicable)

4.55.1

**Comment by itavero** [comment]
Do you still have the Coordinator in your Homebridge cached accessories?
If so, try to remove it: https://github.com/itavero/homebridge-z2m/issues/794#issuecomment-1873409243

**Comment by 1HyperZ** [comment]
> Do you still have the Coordinator in your Homebridge cached accessories?
> If so, try to remove it: https://github.com/itavero/homebridge-z2m/issues/794#issuecomment-1873409243

Thank you so much

**Comment by itavero** [comment]
> Thank you so much

I assume that means the issue is resolved and can be closed?

**Comment by 1HyperZ** [comment]
> 
> > Thank you so much
> 
> I assume that means the issue is resolved and can be closed?
> 

Yes
