### ISSUE TITLE
[Bug] Coordinator device: Cannot read properties of null (reading 'vendor')

### ISSUE THREAD

**Issue by dkerr64** [itavero/homebridge-z2m#853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I updated zigbee2mqtt server to latest (mine was over a year old) and get this...

```
[4/28/2024, 11:26:14 AM] [homebridge-z2m] Restarting Process...
[4/28/2024, 11:26:14 AM] [homebridge-z2m] Launched child bridge with PID 244983
[4/28/2024, 11:26:14 AM] Registering platform 'homebridge-z2m.zigbee2mqtt'
[4/28/2024, 11:26:14 AM] [homebridge-z2m] Loaded homebridge-z2m v1.11.0-beta.2 child bridge successfully
[4/28/2024, 11:26:14 AM] Loaded 31 cached accessories from cachedAccessories.0E706CE49E2D.
[4/28/2024, 11:26:14 AM] [homebridge-z2m] Connecting to MQTT server at mqtt://192.168.29.49:1883
[4/28/2024, 11:26:14 AM] [homebridge-z2m] Restoring accessory: Coordinator (0x00124b0026b87de8)
TypeError: Cannot read properties of null (reading 'vendor')
    at isDeviceDefinition (/var/lib/homebridge/node_modules/homebridge-z2m/src/z2mModels.ts:302:72)
    at Zigbee2mqttAccessory.updateDeviceInformation (/var/lib/homebridge/node_modules/homebridge-z2m/src/platformAccessory.ts:418:30)
    at new Zigbee2mqttAccessory (/var/lib/homebridge/node_modules/homebridge-z2m/src/platformAccessory.ts:98:10)
    at Zigbee2mqttPlatform.addAccessory (/var/lib/homebridge/node_modules/homebridge-z2m/src/platform.ts:575:19)
    at Zigbee2mqttPlatform.configureAccessory (/var/lib/homebridge/node_modules/homebridge-z2m/src/platform.ts:474:10)
    at /var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:328:25
    at Array.filter (<anonymous>)
    at BridgeService.restoreCachedPlatformAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:288:69)
    at ChildBridgeFork.startBridge (/var/lib/homebridge/node_modules/homebridge/src/childBridgeFork.ts:191:24)
[4/28/2024, 11:26:14 AM] [homebridge-z2m] Child bridge process ended
[4/28/2024, 11:26:14 AM] [homebridge-z2m] Process Ended. Code: 1, Signal: null
```

I was able to work around the error by specifically excluding this device.

### This plugin

1.11.0-beta2

### Homebridge

1.8.1

### Zigbee2MQTT

1.36.1

**Comment by dkerr64** [comment]
> @dkerr64 You'll have to completely [exclude](https://z2m.dev/config.html) your coordinator `0x00124b0026b87de8`, save and restart. See also #810

Yes, thanks.  That is exactly what I did.

Sorry, my search did not turn up #810 possibly because I only searched on open issues.  oops.  You can close this as a duplicate if you want.
